[project]
name = "odoo-addons-oca-l10n-france"
version = "18.0.20241201.0"
dependencies = [
    "odoo-addon-l10n_fr_hr_check_ssnid==18.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 18.0",
]
